import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';
import { InferGetStaticPropsType } from 'next';
import { getApiClient } from '../utils/apiQuery';
import Navbar from '@components/navigation/Navbar';
import Button from '@components/buttons/Button';
import DoctorOverviewCard from '@components/cards/DoctorOverViewCard';
import Hero from '@components/hero/Hero';
import Navbar2 from '@components/navigation/Navbar copy';
import Footer from '@components/navigation/Footer';
import ButtonLink from '@components/buttons/ButtonLink';
import { Color } from 'styles/styleEnums';
import DienstenSection from '@components/sections/DienstenSection';

const Home = ({ documents }: InferGetStaticPropsType<GetStaticProps>) => {
  return (
    <div className="relative">
      <Head>
        <title>Onoo Dokters</title>
        <meta name="Onoo Dokters" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        ></link>
      </Head>

      <main className=" mx-auto">
        <Navbar2></Navbar2>
        {/* Hero */}
        <Hero
          subTitle="Olen, Noorderwijk, Morkhoven en Oosterwijk"
          title="Huisartsensamenwerking"
        >
          <ButtonLink
            buttonText="Bekijk alle huisartsen"
            color={Color.BLUE}
            url="#huisartsen"
          />
        </Hero>

        {/* CONTAINER */}
        <div className="max-w-7xl w-5/6 lg:w-full  mx-auto">
          <div id="huisartsen">
            <h2 className=" text-center mb-[32px] mx-auto text-onoo_blue mt-[80px]">
              Onze Huisartsen
            </h2>
            <DoctorOverviewCard
              link="https://google.be"
              name="Dr Dries"
              photo="qq"
              key="test"
            />
          </div>
        </div>
        <DienstenSection diensten={['test']} />
      </main>

      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {},
  };
};

export default Home;
